"""SQL dialect abstraction for SQLite + Postgres support.

The goal is to keep a single :class:`~api_scout.database.Database` class
that speaks both SQLite and Postgres, rather than maintaining two
separate implementations. Most dialect differences are eliminated by
policy (e.g. all timestamps are ISO-8601 strings computed in Python,
stored as ``TEXT`` on both backends). What's left fits into this small
interface:

* ``ph`` — the parameter marker the DB-API driver expects. ``?`` for
  :mod:`sqlite3`; ``%s`` for :mod:`psycopg`. Queries are written with
  ``{ph}`` placeholders and formatted at emit time.
* ``least_sql(a, b)`` / ``greatest_sql(a, b)`` — SQLite uses
  ``MIN(a, b)`` / ``MAX(a, b)`` as scalar functions; Postgres uses
  ``LEAST(a, b)`` / ``GREATEST(a, b)``.
* ``hour_bucket_sql(column)`` — SQLite has ``strftime``; Postgres has
  ``to_char`` or ``date_trunc``.
* ``insert_returning_id(conn, sql, params)`` — SQLite exposes
  ``cursor.lastrowid``; psycopg needs a ``RETURNING id`` clause.
* ``connect(url)`` — driver-specific connection setup.
* ``row_to_dict(row)`` — normalise DB-API rows to plain dicts.

Any query that stays identical on both backends (the vast majority)
doesn't need dialect-aware code at all.

The dialect object is immutable. Callers should obtain one via
:func:`dialect_for_url`.
"""

from __future__ import annotations

import os
import sqlite3
from abc import ABC, abstractmethod
from typing import Any
from urllib.parse import urlparse


# ── Public dialect identifiers ──────────────────────────────────────

SQLITE = "sqlite"
POSTGRES = "postgres"


class SQLDialect(ABC):
    """Abstract SQL dialect. See module docstring."""

    #: Dialect name, matches migration filename suffix.
    name: str = ""
    #: Parameter marker, e.g. ``"?"`` or ``"%s"``.
    ph: str = ""

    # ── SQL fragment helpers ────────────────────────────────────────

    @abstractmethod
    def least_sql(self, *args: str) -> str:
        """Return a SQL expression equivalent to min-of-values."""

    @abstractmethod
    def greatest_sql(self, *args: str) -> str:
        """Return a SQL expression equivalent to max-of-values."""

    @abstractmethod
    def hour_bucket_sql(self, column: str) -> str:
        """Return a SQL expression that truncates ``column`` to the hour,
        formatted as ``YYYY-MM-DDTHH:00:00``."""

    @abstractmethod
    def integrity_error_type(self) -> type[Exception]:
        """Return the driver-specific IntegrityError class. Callers
        that want to catch unique-constraint violations should catch
        this rather than importing the driver directly."""

    # ── Connection lifecycle ────────────────────────────────────────

    @abstractmethod
    def connect(self, url: str) -> Any:
        """Open a new connection to the URL. Caller owns the connection."""

    @abstractmethod
    def row_to_dict(self, row: Any) -> dict | None:
        """Convert a fetched row to a plain dict (or None for None)."""

    # ── Insert+return id ────────────────────────────────────────────

    @abstractmethod
    def insert_returning_id(self, conn: Any, sql: str, params: tuple) -> int:
        """Execute ``sql`` and return the autogenerated integer id.

        On SQLite this is ``cursor.lastrowid``. On Postgres the caller
        is expected to have written ``sql`` without a trailing
        ``RETURNING id`` — this method appends it.
        """


# ── SQLite implementation ───────────────────────────────────────────


class SQLiteDialect(SQLDialect):
    name = SQLITE
    ph = "?"

    def __init__(self, path: str):
        self.path = path

    def least_sql(self, *args: str) -> str:
        # SQLite: MIN as a scalar function. Accepts any number of args.
        return f"MIN({', '.join(args)})"

    def greatest_sql(self, *args: str) -> str:
        return f"MAX({', '.join(args)})"

    def hour_bucket_sql(self, column: str) -> str:
        return f"strftime('%Y-%m-%dT%H:00:00', {column})"

    def integrity_error_type(self) -> type[Exception]:
        return sqlite3.IntegrityError

    def connect(self, url: str) -> sqlite3.Connection:
        # ``url`` may be a ``sqlite:///path`` URL or a bare path; both
        # are supported for backward compat with callers that still
        # pass ``Path`` objects.
        path = _sqlite_path_from_url(url) if url.startswith("sqlite:") else url
        conn = sqlite3.connect(path)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA foreign_keys=ON")
        return conn

    def row_to_dict(self, row: Any) -> dict | None:
        if row is None:
            return None
        # sqlite3.Row supports dict() directly.
        return dict(row)

    def insert_returning_id(self, conn: Any, sql: str, params: tuple) -> int:
        cur = conn.execute(sql, params)
        return int(cur.lastrowid)


# ── Postgres implementation ─────────────────────────────────────────


class PostgresDialect(SQLDialect):
    name = POSTGRES
    ph = "%s"

    def least_sql(self, *args: str) -> str:
        return f"LEAST({', '.join(args)})"

    def greatest_sql(self, *args: str) -> str:
        return f"GREATEST({', '.join(args)})"

    def hour_bucket_sql(self, column: str) -> str:
        # to_char on a TEXT column requires a cast to timestamp first.
        # Storage is TEXT ISO-8601 on both backends (see module docstring).
        return f"to_char(({column})::timestamp, 'YYYY-MM-DD\"T\"HH24:\"00:00\"')"

    def integrity_error_type(self) -> type[Exception]:
        # Lazy import: psycopg is an optional dep.
        import psycopg  # type: ignore[import-not-found]

        return psycopg.errors.IntegrityError

    def connect(self, url: str) -> Any:
        import psycopg  # type: ignore[import-not-found]
        from psycopg.rows import dict_row  # type: ignore[import-not-found]

        conn = psycopg.connect(url, row_factory=dict_row)
        # Match SQLite-ish semantics: transactions are explicit, callers
        # .commit() or .rollback() as needed. psycopg's default is
        # already non-autocommit, but we make it explicit.
        conn.autocommit = False
        return conn

    def row_to_dict(self, row: Any) -> dict | None:
        if row is None:
            return None
        # dict_row gives us dicts already.
        return dict(row)

    def insert_returning_id(self, conn: Any, sql: str, params: tuple) -> int:
        # psycopg: append RETURNING id and read it back.
        # The caller passes a raw INSERT without RETURNING.
        s = sql.rstrip().rstrip(";")
        if "RETURNING" not in s.upper():
            s = s + " RETURNING id"
        cur = conn.execute(s, params)
        row = cur.fetchone()
        if row is None:
            raise RuntimeError("INSERT ... RETURNING id produced no row")
        # dict_row gives us {'id': <n>}; fall back to index for tuple-rows.
        if isinstance(row, dict):
            return int(row["id"])
        return int(row[0])


# ── URL parsing / factory ───────────────────────────────────────────


def _sqlite_path_from_url(url: str) -> str:
    """Extract a filesystem path from a sqlite URL.

    Accepts:
      * ``sqlite:///absolute/path.db``  (note the three slashes: empty host)
      * ``sqlite://relative/path.db``   (two slashes: rel path - tolerated)
      * ``sqlite::memory:``             (in-memory - tolerated convenience)
    """
    if url == "sqlite::memory:" or url == "sqlite:///:memory:":
        return ":memory:"
    parsed = urlparse(url)
    # urlparse gives ``path`` starting with a leading slash for the
    # standard sqlite:/// form, which is exactly what we want on *nix.
    # On Windows the path parsing is slightly fiddlier; we stick to the
    # *nix convention because our target is the Docker image anyway.
    if parsed.path:
        return parsed.path
    if parsed.netloc:
        return parsed.netloc
    raise ValueError(f"Could not derive a filesystem path from sqlite URL: {url!r}")


def dialect_for_url(url: str) -> SQLDialect:
    """Return the right :class:`SQLDialect` for a given URL.

    Supported schemes:

    * ``sqlite:///path/to/file.db`` (also accepts a bare filesystem path)
    * ``sqlite::memory:``
    * ``postgresql://...``  /  ``postgres://...``

    Passing a bare filesystem path (anything without a scheme prefix
    recognised as a DB URL) is treated as SQLite for backward compat
    — callers in the existing codebase pass a :class:`pathlib.Path` to
    ``Database(...)``.
    """
    if url.startswith("postgresql://") or url.startswith("postgres://"):
        return PostgresDialect()
    if url.startswith("sqlite:"):
        return SQLiteDialect(path=_sqlite_path_from_url(url))
    # Bare path / anything else → SQLite.
    return SQLiteDialect(path=url)


def database_url_from_env(default: str | None = None) -> str | None:
    """Return the DB URL from ``API_SCOUT_DATABASE_URL`` if set.

    Returns ``default`` (which may be None) if the env var is unset.
    """
    return os.environ.get("API_SCOUT_DATABASE_URL", default)
