"""Auto-Remediation — WAF Rule Generation & OpenAPI Spec Generation.

Turns discovery findings into actionable outputs:
- Generate WAF rules (AWS WAF, Nginx, ModSecurity) to block shadow APIs
- Auto-generate OpenAPI specs from observed traffic for undocumented endpoints
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime
from typing import Optional

from .database import Database
from .models import APIEndpoint, APIStatus, AuthMethod


# ═══════════════════════════════════════════════════
#  WAF Rule Generation
# ═══════════════════════════════════════════════════


class WAFRuleGenerator:
    """Generate WAF rules to block or alert on shadow/unauthorized API endpoints."""

    def __init__(self, db: Database):
        self.db = db

    def generate_nginx_rules(
        self,
        endpoints: list[APIEndpoint] | None = None,
        action: str = "deny",  # "deny" or "return 403"
    ) -> str:
        """Generate Nginx location blocks to block shadow APIs."""
        if endpoints is None:
            endpoints = self.db.get_endpoints_by_status(APIStatus.SHADOW)

        lines = [
            "# ═══════════════════════════════════════════════",
            "# API Scout — Auto-Generated Shadow API Block Rules",
            f"# Generated: {datetime.now().isoformat()}",
            f"# Endpoints: {len(endpoints)}",
            "# ═══════════════════════════════════════════════",
            "",
        ]

        for ep in endpoints:
            # Convert path pattern to Nginx regex
            nginx_path = _path_to_nginx_regex(ep.path_pattern)
            method_check = f'if ($request_method = {ep.method}) ' + '{'

            lines.extend([
                f"# Shadow API: {ep.method} {ep.path_pattern}",
                f"# Calls: {ep.total_calls}, First seen: {ep.first_seen}",
                f"location ~ ^{nginx_path}$ {{",
                f"    {method_check}",
                f"        {action};",
                "    }",
                "}",
                "",
            ])

        return "\n".join(lines)

    def generate_aws_waf_rules(
        self,
        endpoints: list[APIEndpoint] | None = None,
    ) -> dict:
        """Generate AWS WAF rule set JSON to block shadow APIs."""
        if endpoints is None:
            endpoints = self.db.get_endpoints_by_status(APIStatus.SHADOW)

        rules = []
        for i, ep in enumerate(endpoints):
            regex_path = _path_to_waf_regex(ep.path_pattern)
            rules.append({
                "Name": f"BlockShadowAPI_{i}",
                "Priority": 100 + i,
                "Statement": {
                    "AndStatement": {
                        "Statements": [
                            {
                                "ByteMatchStatement": {
                                    "FieldToMatch": {"Method": {}},
                                    "PositionalConstraint": "EXACTLY",
                                    "SearchString": ep.method,
                                    "TextTransformations": [{"Priority": 0, "Type": "NONE"}],
                                }
                            },
                            {
                                "RegexPatternSetReferenceStatement": {
                                    "ARN": "PLACEHOLDER_ARN",
                                    "FieldToMatch": {"UriPath": {}},
                                    "TextTransformations": [{"Priority": 0, "Type": "NONE"}],
                                }
                            },
                        ]
                    }
                },
                "Action": {"Block": {}},
                "VisibilityConfig": {
                    "SampledRequestsEnabled": True,
                    "CloudWatchMetricsEnabled": True,
                    "MetricName": f"BlockShadowAPI_{ep.method}_{_sanitize(ep.path_pattern)}",
                },
            })

        return {
            "_comment": f"Generated by API Scout at {datetime.now().isoformat()}",
            "Name": "APIScout-ShadowAPIBlockRules",
            "Scope": "REGIONAL",
            "DefaultAction": {"Allow": {}},
            "Rules": rules,
            "VisibilityConfig": {
                "SampledRequestsEnabled": True,
                "CloudWatchMetricsEnabled": True,
                "MetricName": "APIScoutShadowAPIRules",
            },
        }

    def generate_modsecurity_rules(
        self,
        endpoints: list[APIEndpoint] | None = None,
    ) -> str:
        """Generate ModSecurity rules to block shadow APIs."""
        if endpoints is None:
            endpoints = self.db.get_endpoints_by_status(APIStatus.SHADOW)

        lines = [
            "# ═══════════════════════════════════════════════",
            "# API Scout — ModSecurity Shadow API Block Rules",
            f"# Generated: {datetime.now().isoformat()}",
            "# ═══════════════════════════════════════════════",
            "",
        ]

        for i, ep in enumerate(endpoints):
            rule_id = 900000 + i
            regex_path = _path_to_waf_regex(ep.path_pattern)
            lines.append(
                f'SecRule REQUEST_URI "@rx ^{regex_path}$" '
                f'"id:{rule_id},'
                f'phase:1,'
                f'deny,'
                f'status:403,'
                f'msg:\'API Scout: Blocked shadow API {ep.method} {ep.path_pattern}\','
                f'chain"'
            )
            lines.append(
                f'    SecRule REQUEST_METHOD "@streq {ep.method}" ""'
            )
            lines.append("")

        return "\n".join(lines)


# ═══════════════════════════════════════════════════
#  OpenAPI Spec Auto-Generation
# ═══════════════════════════════════════════════════


class SpecGenerator:
    """Auto-generate OpenAPI specs from observed traffic patterns."""

    def __init__(self, db: Database):
        self.db = db

    def generate_spec(
        self,
        endpoints: list[APIEndpoint] | None = None,
        title: str = "Auto-Generated API Spec",
        version: str = "1.0.0",
        description: str | None = None,
    ) -> dict:
        """Generate a complete OpenAPI 3.0 spec from discovered endpoints."""
        if endpoints is None:
            endpoints = self.db.get_all_endpoints()

        spec = {
            "openapi": "3.0.3",
            "info": {
                "title": title,
                "version": version,
                "description": description or (
                    f"Auto-generated by API Scout from observed traffic. "
                    f"Generated: {datetime.now().isoformat()}. "
                    f"Endpoints: {len(endpoints)}."
                ),
            },
            "paths": {},
            "components": {
                "securitySchemes": self._infer_security_schemes(endpoints),
            },
        }

        # Group endpoints by path
        path_groups: dict[str, list[APIEndpoint]] = defaultdict(list)
        for ep in endpoints:
            path_groups[ep.path_pattern].append(ep)

        # Build servers list from unique hosts
        hosts = set(ep.host for ep in endpoints if ep.host)
        if hosts:
            spec["servers"] = [{"url": f"https://{h}"} for h in sorted(hosts)]

        for path, eps in sorted(path_groups.items()):
            path_item = {}
            for ep in eps:
                operation = self._build_operation(ep)
                path_item[ep.method.lower()] = operation

            spec["paths"][path] = path_item

        return spec

    def generate_for_undocumented(self, **kwargs) -> dict:
        """Generate spec only for undocumented/shadow endpoints."""
        undocumented = [
            ep for ep in self.db.get_all_endpoints()
            if not ep.declared_in_spec
        ]
        return self.generate_spec(
            endpoints=undocumented,
            title=kwargs.get("title", "Undocumented APIs — Needs Review"),
            description=(
                "These endpoints were discovered through traffic analysis "
                "but are not declared in any existing OpenAPI spec. "
                "Please review and document them."
            ),
            **{k: v for k, v in kwargs.items() if k not in ("title", "description")},
        )

    def _build_operation(self, ep: APIEndpoint) -> dict:
        """Build an OpenAPI operation object from an endpoint."""
        operation: dict = {
            "summary": f"[Auto-discovered] {ep.method} {ep.path_pattern}",
            "description": self._build_description(ep),
            "responses": self._infer_responses(ep),
        }

        if ep.status == APIStatus.DEPRECATED:
            operation["deprecated"] = True

        # Add tags based on path prefix
        tags = self._infer_tags(ep.path_pattern)
        if tags:
            operation["tags"] = tags

        # Add operationId
        operation["operationId"] = _generate_operation_id(ep.method, ep.path_pattern)

        # Add path parameters
        params = self._extract_path_params(ep.path_pattern)
        if params:
            operation["parameters"] = params

        # Add security requirements
        security = self._infer_security(ep)
        if security:
            operation["security"] = security

        return operation

    def _build_description(self, ep: APIEndpoint) -> str:
        """Build a description with discovery metadata."""
        lines = [
            f"**Auto-discovered by API Scout**\n",
            f"- **Status:** {ep.status.value}",
            f"- **Total calls observed:** {ep.total_calls}",
            f"- **Error rate:** {ep.error_rate:.1%}",
            f"- **Consumers:** {len(ep.consumers)}",
        ]
        if ep.first_seen:
            lines.append(f"- **First seen:** {ep.first_seen.isoformat()}")
        if ep.last_seen:
            lines.append(f"- **Last seen:** {ep.last_seen.isoformat()}")
        if ep.avg_response_time_ms:
            lines.append(f"- **Avg latency:** {ep.avg_response_time_ms:.0f}ms")

        lines.append(f"\n> Review this endpoint and replace this auto-generated documentation.")
        return "\n".join(lines)

    def _infer_responses(self, ep: APIEndpoint) -> dict:
        """Infer response codes from observed traffic."""
        responses = {}

        # We know the endpoint exists, so assume 200 for GET, 201 for POST, etc.
        success_code = {
            "GET": "200",
            "POST": "201",
            "PUT": "200",
            "PATCH": "200",
            "DELETE": "204",
        }.get(ep.method, "200")

        responses[success_code] = {
            "description": "Successful response (inferred from traffic)",
        }

        if ep.error_count > 0:
            if ep.error_rate > 0.5:
                responses["500"] = {"description": "Server error (high error rate observed)"}
            else:
                responses["400"] = {"description": "Client error (errors observed in traffic)"}

        # If unauthenticated traffic was seen, document 401
        if AuthMethod.NONE in ep.auth_methods_seen and len(ep.auth_methods_seen) > 1:
            responses["401"] = {"description": "Authentication required"}

        return responses

    def _infer_security(self, ep: APIEndpoint) -> list[dict]:
        """Infer security requirements from observed auth methods."""
        security = []
        for auth in ep.auth_methods_seen:
            if auth == AuthMethod.BEARER:
                security.append({"bearerAuth": []})
            elif auth == AuthMethod.API_KEY:
                security.append({"apiKeyAuth": []})
            elif auth == AuthMethod.BASIC:
                security.append({"basicAuth": []})
        return security if security else [{}]  # Empty object = no auth required

    def _infer_security_schemes(self, endpoints: list[APIEndpoint]) -> dict:
        """Infer security scheme definitions from all endpoints."""
        schemes = {}
        all_auth = set()
        for ep in endpoints:
            all_auth.update(ep.auth_methods_seen)

        if AuthMethod.BEARER in all_auth:
            schemes["bearerAuth"] = {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "Inferred from observed Bearer tokens in traffic",
            }
        if AuthMethod.API_KEY in all_auth:
            schemes["apiKeyAuth"] = {
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key",
                "description": "Inferred from observed API key headers",
            }
        if AuthMethod.BASIC in all_auth:
            schemes["basicAuth"] = {
                "type": "http",
                "scheme": "basic",
                "description": "Inferred from observed Basic auth headers",
            }

        return schemes

    @staticmethod
    def _extract_path_params(path_pattern: str) -> list[dict]:
        """Extract path parameters from a pattern like /users/{id}."""
        import re
        params = []
        for match in re.finditer(r'\{(\w+)\}', path_pattern):
            param_name = match.group(1)
            params.append({
                "name": param_name,
                "in": "path",
                "required": True,
                "schema": {"type": "string"},
                "description": f"Auto-detected path parameter: {param_name}",
            })
        return params

    @staticmethod
    def _infer_tags(path: str) -> list[str]:
        """Infer API tags from path prefix."""
        parts = path.strip("/").split("/")
        # Skip version prefix (v1, v2, api, etc.)
        meaningful = [p for p in parts if not p.startswith(("v1", "v2", "v3", "api", "{"))]
        if meaningful:
            return [meaningful[0].replace("_", " ").replace("-", " ").title()]
        return []


# ═══════════════════════════════════════════════════
#  Utilities
# ═══════════════════════════════════════════════════


def _path_to_nginx_regex(path_pattern: str) -> str:
    """Convert /users/{id}/orders to /users/[^/]+/orders."""
    import re
    return re.sub(r'\{[^}]+\}', '[^/]+', path_pattern)


def _path_to_waf_regex(path_pattern: str) -> str:
    """Convert /users/{id}/orders to /users/[^/]+/orders."""
    import re
    return re.sub(r'\{[^}]+\}', '[^/]+', path_pattern)


def _sanitize(s: str) -> str:
    """Sanitize a string for metric names."""
    import re
    return re.sub(r'[^A-Za-z0-9]', '_', s).strip('_')


def _generate_operation_id(method: str, path: str) -> str:
    """Generate a camelCase operationId from method + path."""
    parts = path.strip("/").split("/")
    words = []
    for p in parts:
        if p.startswith("{"):
            words.append("By" + p.strip("{}").title())
        elif not p.startswith(("v1", "v2", "v3", "api")):
            words.append(p.replace("-", "_").title())

    return method.lower() + "".join(words)
